// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: csmsg.proto
// Protobuf C++ Version: 6.33.0

#include "csmsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace LocalPhotoSync {
template <typename>
PROTOBUF_CONSTEXPR CSResSyncPhoto::CSResSyncPhoto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(CSResSyncPhoto_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CSResSyncPhotoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSResSyncPhotoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSResSyncPhotoDefaultTypeInternal() {}
  union {
    CSResSyncPhoto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSResSyncPhotoDefaultTypeInternal _CSResSyncPhoto_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CSResDeviceInfo::CSResDeviceInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(CSResDeviceInfo_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CSResDeviceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSResDeviceInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSResDeviceInfoDefaultTypeInternal() {}
  union {
    CSResDeviceInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSResDeviceInfoDefaultTypeInternal _CSResDeviceInfo_default_instance_;

inline constexpr CSReqSyncPhoto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{::uint64_t{0u}},
        offset_{::uint64_t{0u}},
        timestamp_{::uint64_t{0u}},
        hasnextpkt_{false},
        crc32_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CSReqSyncPhoto::CSReqSyncPhoto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CSReqSyncPhoto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CSReqSyncPhotoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSReqSyncPhotoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSReqSyncPhotoDefaultTypeInternal() {}
  union {
    CSReqSyncPhoto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSReqSyncPhotoDefaultTypeInternal _CSReqSyncPhoto_default_instance_;

inline constexpr CSReqDeviceInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        deviceid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CSReqDeviceInfo::CSReqDeviceInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CSReqDeviceInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CSReqDeviceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSReqDeviceInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSReqDeviceInfoDefaultTypeInternal() {}
  union {
    CSReqDeviceInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSReqDeviceInfoDefaultTypeInternal _CSReqDeviceInfo_default_instance_;

inline constexpr CSNtyServerInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rootpath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        os_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tcpport_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CSNtyServerInfo::CSNtyServerInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CSNtyServerInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CSNtyServerInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSNtyServerInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSNtyServerInfoDefaultTypeInternal() {}
  union {
    CSNtyServerInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSNtyServerInfoDefaultTypeInternal _CSNtyServerInfo_default_instance_;

inline constexpr MsgPkg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        serialid_{::uint64_t{0u}},
        resultid_{0},
        MsgBody_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MsgPkg::MsgPkg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MsgPkg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MsgPkgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgPkgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgPkgDefaultTypeInternal() {}
  union {
    MsgPkg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgPkgDefaultTypeInternal _MsgPkg_default_instance_;
}  // namespace LocalPhotoSync
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_csmsg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_csmsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_csmsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_._oneof_case_[0]),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.resultid_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.serialid_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_.MsgBody_),
        1,
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSNtyServerInfo, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSNtyServerInfo, _impl_.tcpport_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSNtyServerInfo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSNtyServerInfo, _impl_.rootpath_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSNtyServerInfo, _impl_.os_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqDeviceInfo, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqDeviceInfo, _impl_.deviceid_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqDeviceInfo, _impl_.path_),
        0,
        1,
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.offset_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.hasnextpkt_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::CSReqSyncPhoto, _impl_.crc32_),
        0,
        2,
        3,
        4,
        5,
        1,
        6,
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::LocalPhotoSync::MsgPkg)},
        {19, sizeof(::LocalPhotoSync::CSNtyServerInfo)},
        {30, sizeof(::LocalPhotoSync::CSReqDeviceInfo)},
        {37, sizeof(::LocalPhotoSync::CSResDeviceInfo)},
        {38, sizeof(::LocalPhotoSync::CSReqSyncPhoto)},
        {55, sizeof(::LocalPhotoSync::CSResSyncPhoto)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::LocalPhotoSync::_MsgPkg_default_instance_._instance,
    &::LocalPhotoSync::_CSNtyServerInfo_default_instance_._instance,
    &::LocalPhotoSync::_CSReqDeviceInfo_default_instance_._instance,
    &::LocalPhotoSync::_CSResDeviceInfo_default_instance_._instance,
    &::LocalPhotoSync::_CSReqSyncPhoto_default_instance_._instance,
    &::LocalPhotoSync::_CSResSyncPhoto_default_instance_._instance,
};
const char descriptor_table_protodef_csmsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013csmsg.proto\022\016LocalPhotoSync\"\337\002\n\006MsgPkg"
    "\022\020\n\010ResultID\030\001 \001(\005\022\020\n\010SerialID\030\002 \001(\004\022:\n\017"
    "CSNtyServerInfo\0302 \001(\0132\037.LocalPhotoSync.C"
    "SNtyServerInfoH\000\022:\n\017CSReqDeviceInfo\030e \001("
    "\0132\037.LocalPhotoSync.CSReqDeviceInfoH\000\022:\n\017"
    "CSResDeviceInfo\030f \001(\0132\037.LocalPhotoSync.C"
    "SResDeviceInfoH\000\0228\n\016CSReqSyncPhoto\030g \001(\013"
    "2\036.LocalPhotoSync.CSReqSyncPhotoH\000\0228\n\016CS"
    "ResSyncPhoto\030h \001(\0132\036.LocalPhotoSync.CSRe"
    "sSyncPhotoH\000B\t\n\007MsgBody\"N\n\017CSNtyServerIn"
    "fo\022\017\n\007TcpPort\030\001 \001(\r\022\014\n\004Name\030\002 \001(\t\022\020\n\010Roo"
    "tPath\030\003 \001(\t\022\n\n\002OS\030\004 \001(\t\"1\n\017CSReqDeviceIn"
    "fo\022\020\n\010DeviceID\030\001 \001(\t\022\014\n\004Path\030\002 \001(\t\"\021\n\017CS"
    "ResDeviceInfo\"\204\001\n\016CSReqSyncPhoto\022\020\n\010File"
    "name\030\001 \001(\t\022\014\n\004Size\030\002 \001(\004\022\016\n\006Offset\030\003 \001(\004"
    "\022\021\n\tTimestamp\030\004 \001(\004\022\022\n\nHasNextPkt\030\005 \001(\010\022"
    "\014\n\004Data\030\006 \001(\014\022\r\n\005Crc32\030\007 \001(\r\"\020\n\016CSResSyn"
    "cPhotob\006proto3"
};
static ::absl::once_flag descriptor_table_csmsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_csmsg_2eproto = {
    false,
    false,
    694,
    descriptor_table_protodef_csmsg_2eproto,
    "csmsg.proto",
    &descriptor_table_csmsg_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_csmsg_2eproto::offsets,
    file_level_enum_descriptors_csmsg_2eproto,
    file_level_service_descriptors_csmsg_2eproto,
};
namespace LocalPhotoSync {
// ===================================================================

class MsgPkg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MsgPkg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::LocalPhotoSync::MsgPkg, _impl_._oneof_case_);
};

void MsgPkg::set_allocated_csntyserverinfo(::LocalPhotoSync::CSNtyServerInfo* PROTOBUF_NULLABLE csntyserverinfo) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_MsgBody();
  if (csntyserverinfo) {
    ::google::protobuf::Arena* submessage_arena = csntyserverinfo->GetArena();
    if (message_arena != submessage_arena) {
      csntyserverinfo = ::google::protobuf::internal::GetOwnedMessage(message_arena, csntyserverinfo, submessage_arena);
    }
    set_has_csntyserverinfo();
    _impl_.MsgBody_.csntyserverinfo_ = csntyserverinfo;
  }
  // @@protoc_insertion_point(field_set_allocated:LocalPhotoSync.MsgPkg.CSNtyServerInfo)
}
void MsgPkg::set_allocated_csreqdeviceinfo(::LocalPhotoSync::CSReqDeviceInfo* PROTOBUF_NULLABLE csreqdeviceinfo) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_MsgBody();
  if (csreqdeviceinfo) {
    ::google::protobuf::Arena* submessage_arena = csreqdeviceinfo->GetArena();
    if (message_arena != submessage_arena) {
      csreqdeviceinfo = ::google::protobuf::internal::GetOwnedMessage(message_arena, csreqdeviceinfo, submessage_arena);
    }
    set_has_csreqdeviceinfo();
    _impl_.MsgBody_.csreqdeviceinfo_ = csreqdeviceinfo;
  }
  // @@protoc_insertion_point(field_set_allocated:LocalPhotoSync.MsgPkg.CSReqDeviceInfo)
}
void MsgPkg::set_allocated_csresdeviceinfo(::LocalPhotoSync::CSResDeviceInfo* PROTOBUF_NULLABLE csresdeviceinfo) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_MsgBody();
  if (csresdeviceinfo) {
    ::google::protobuf::Arena* submessage_arena = csresdeviceinfo->GetArena();
    if (message_arena != submessage_arena) {
      csresdeviceinfo = ::google::protobuf::internal::GetOwnedMessage(message_arena, csresdeviceinfo, submessage_arena);
    }
    set_has_csresdeviceinfo();
    _impl_.MsgBody_.csresdeviceinfo_ = csresdeviceinfo;
  }
  // @@protoc_insertion_point(field_set_allocated:LocalPhotoSync.MsgPkg.CSResDeviceInfo)
}
void MsgPkg::set_allocated_csreqsyncphoto(::LocalPhotoSync::CSReqSyncPhoto* PROTOBUF_NULLABLE csreqsyncphoto) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_MsgBody();
  if (csreqsyncphoto) {
    ::google::protobuf::Arena* submessage_arena = csreqsyncphoto->GetArena();
    if (message_arena != submessage_arena) {
      csreqsyncphoto = ::google::protobuf::internal::GetOwnedMessage(message_arena, csreqsyncphoto, submessage_arena);
    }
    set_has_csreqsyncphoto();
    _impl_.MsgBody_.csreqsyncphoto_ = csreqsyncphoto;
  }
  // @@protoc_insertion_point(field_set_allocated:LocalPhotoSync.MsgPkg.CSReqSyncPhoto)
}
void MsgPkg::set_allocated_csressyncphoto(::LocalPhotoSync::CSResSyncPhoto* PROTOBUF_NULLABLE csressyncphoto) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_MsgBody();
  if (csressyncphoto) {
    ::google::protobuf::Arena* submessage_arena = csressyncphoto->GetArena();
    if (message_arena != submessage_arena) {
      csressyncphoto = ::google::protobuf::internal::GetOwnedMessage(message_arena, csressyncphoto, submessage_arena);
    }
    set_has_csressyncphoto();
    _impl_.MsgBody_.csressyncphoto_ = csressyncphoto;
  }
  // @@protoc_insertion_point(field_set_allocated:LocalPhotoSync.MsgPkg.CSResSyncPhoto)
}
MsgPkg::MsgPkg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MsgPkg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.MsgPkg)
}
PROTOBUF_NDEBUG_INLINE MsgPkg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::LocalPhotoSync::MsgPkg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        MsgBody_{},
        _oneof_case_{from._oneof_case_[0]} {}

MsgPkg::MsgPkg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MsgPkg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MsgPkg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MsgPkg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, serialid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, serialid_),
           offsetof(Impl_, resultid_) -
               offsetof(Impl_, serialid_) +
               sizeof(Impl_::resultid_));
  switch (MsgBody_case()) {
    case MSGBODY_NOT_SET:
      break;
      case kCSNtyServerInfo:
        _impl_.MsgBody_.csntyserverinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csntyserverinfo_);
        break;
      case kCSReqDeviceInfo:
        _impl_.MsgBody_.csreqdeviceinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csreqdeviceinfo_);
        break;
      case kCSResDeviceInfo:
        _impl_.MsgBody_.csresdeviceinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csresdeviceinfo_);
        break;
      case kCSReqSyncPhoto:
        _impl_.MsgBody_.csreqsyncphoto_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csreqsyncphoto_);
        break;
      case kCSResSyncPhoto:
        _impl_.MsgBody_.csressyncphoto_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csressyncphoto_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.MsgPkg)
}
PROTOBUF_NDEBUG_INLINE MsgPkg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        MsgBody_{},
        _oneof_case_{} {}

inline void MsgPkg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, serialid_),
           0,
           offsetof(Impl_, resultid_) -
               offsetof(Impl_, serialid_) +
               sizeof(Impl_::resultid_));
}
MsgPkg::~MsgPkg() {
  // @@protoc_insertion_point(destructor:LocalPhotoSync.MsgPkg)
  SharedDtor(*this);
}
inline void MsgPkg::SharedDtor(MessageLite& self) {
  MsgPkg& this_ = static_cast<MsgPkg&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_MsgBody()) {
    this_.clear_MsgBody();
  }
  this_._impl_.~Impl_();
}

void MsgPkg::clear_MsgBody() {
// @@protoc_insertion_point(one_of_clear_start:LocalPhotoSync.MsgPkg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (MsgBody_case()) {
    case kCSNtyServerInfo: {
      if (GetArena() == nullptr) {
        delete _impl_.MsgBody_.csntyserverinfo_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.MsgBody_.csntyserverinfo_);
      }
      break;
    }
    case kCSReqDeviceInfo: {
      if (GetArena() == nullptr) {
        delete _impl_.MsgBody_.csreqdeviceinfo_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.MsgBody_.csreqdeviceinfo_);
      }
      break;
    }
    case kCSResDeviceInfo: {
      if (GetArena() == nullptr) {
        delete _impl_.MsgBody_.csresdeviceinfo_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.MsgBody_.csresdeviceinfo_);
      }
      break;
    }
    case kCSReqSyncPhoto: {
      if (GetArena() == nullptr) {
        delete _impl_.MsgBody_.csreqsyncphoto_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.MsgBody_.csreqsyncphoto_);
      }
      break;
    }
    case kCSResSyncPhoto: {
      if (GetArena() == nullptr) {
        delete _impl_.MsgBody_.csressyncphoto_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.MsgBody_.csressyncphoto_);
      }
      break;
    }
    case MSGBODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MSGBODY_NOT_SET;
}


inline void* PROTOBUF_NONNULL MsgPkg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MsgPkg(arena);
}
constexpr auto MsgPkg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MsgPkg),
                                            alignof(MsgPkg));
}
constexpr auto MsgPkg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MsgPkg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MsgPkg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MsgPkg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MsgPkg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MsgPkg>(), &MsgPkg::ByteSizeLong,
              &MsgPkg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_._cached_size_),
          false,
      },
      &MsgPkg::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MsgPkg_class_data_ =
        MsgPkg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MsgPkg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MsgPkg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MsgPkg_class_data_.tc_table);
  return MsgPkg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 7, 5, 0, 13>
MsgPkg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_._has_bits_),
    0, // no _extensions_
    104, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MsgPkg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::MsgPkg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 SerialID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgPkg, _impl_.serialid_), 0>(),
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.serialid_)}},
    // int32 ResultID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MsgPkg, _impl_.resultid_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.resultid_)}},
  }}, {{
    50, 0, 4,
    65534, 2,
    65535, 3,
    65535, 3,
    65415, 3,
    65535, 65535
  }}, {{
    // int32 ResultID = 1;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.resultid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // uint64 SerialID = 2;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.serialid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .LocalPhotoSync.CSNtyServerInfo CSNtyServerInfo = 50;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.MsgBody_.csntyserverinfo_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LocalPhotoSync.CSReqDeviceInfo CSReqDeviceInfo = 101;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.MsgBody_.csreqdeviceinfo_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LocalPhotoSync.CSResDeviceInfo CSResDeviceInfo = 102;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.MsgBody_.csresdeviceinfo_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LocalPhotoSync.CSReqSyncPhoto CSReqSyncPhoto = 103;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.MsgBody_.csreqsyncphoto_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LocalPhotoSync.CSResSyncPhoto CSResSyncPhoto = 104;
    {PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.MsgBody_.csressyncphoto_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::LocalPhotoSync::CSNtyServerInfo>()},
      {::_pbi::TcParser::GetTable<::LocalPhotoSync::CSReqDeviceInfo>()},
      {::_pbi::TcParser::GetTable<::LocalPhotoSync::CSResDeviceInfo>()},
      {::_pbi::TcParser::GetTable<::LocalPhotoSync::CSReqSyncPhoto>()},
      {::_pbi::TcParser::GetTable<::LocalPhotoSync::CSResSyncPhoto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void MsgPkg::Clear() {
// @@protoc_insertion_point(message_clear_start:LocalPhotoSync.MsgPkg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.serialid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.resultid_) -
        reinterpret_cast<char*>(&_impl_.serialid_)) + sizeof(_impl_.resultid_));
  }
  clear_MsgBody();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MsgPkg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MsgPkg& this_ = static_cast<const MsgPkg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MsgPkg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MsgPkg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:LocalPhotoSync.MsgPkg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 ResultID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_resultid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_resultid(), target);
    }
  }

  // uint64 SerialID = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_serialid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_serialid(), target);
    }
  }

  switch (this_.MsgBody_case()) {
    case kCSNtyServerInfo: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          50, *this_._impl_.MsgBody_.csntyserverinfo_, this_._impl_.MsgBody_.csntyserverinfo_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCSReqDeviceInfo: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          101, *this_._impl_.MsgBody_.csreqdeviceinfo_, this_._impl_.MsgBody_.csreqdeviceinfo_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCSResDeviceInfo: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          102, *this_._impl_.MsgBody_.csresdeviceinfo_, this_._impl_.MsgBody_.csresdeviceinfo_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCSReqSyncPhoto: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          103, *this_._impl_.MsgBody_.csreqsyncphoto_, this_._impl_.MsgBody_.csreqsyncphoto_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCSResSyncPhoto: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          104, *this_._impl_.MsgBody_.csressyncphoto_, this_._impl_.MsgBody_.csressyncphoto_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LocalPhotoSync.MsgPkg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MsgPkg::ByteSizeLong(const MessageLite& base) {
  const MsgPkg& this_ = static_cast<const MsgPkg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MsgPkg::ByteSizeLong() const {
  const MsgPkg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LocalPhotoSync.MsgPkg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // uint64 SerialID = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_serialid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_serialid());
      }
    }
    // int32 ResultID = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_resultid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_resultid());
      }
    }
  }
  switch (this_.MsgBody_case()) {
    // .LocalPhotoSync.CSNtyServerInfo CSNtyServerInfo = 50;
    case kCSNtyServerInfo: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.MsgBody_.csntyserverinfo_);
      break;
    }
    // .LocalPhotoSync.CSReqDeviceInfo CSReqDeviceInfo = 101;
    case kCSReqDeviceInfo: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.MsgBody_.csreqdeviceinfo_);
      break;
    }
    // .LocalPhotoSync.CSResDeviceInfo CSResDeviceInfo = 102;
    case kCSResDeviceInfo: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.MsgBody_.csresdeviceinfo_);
      break;
    }
    // .LocalPhotoSync.CSReqSyncPhoto CSReqSyncPhoto = 103;
    case kCSReqSyncPhoto: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.MsgBody_.csreqsyncphoto_);
      break;
    }
    // .LocalPhotoSync.CSResSyncPhoto CSResSyncPhoto = 104;
    case kCSResSyncPhoto: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.MsgBody_.csressyncphoto_);
      break;
    }
    case MSGBODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MsgPkg::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MsgPkg*>(&to_msg);
  auto& from = static_cast<const MsgPkg&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:LocalPhotoSync.MsgPkg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_serialid() != 0) {
        _this->_impl_.serialid_ = from._impl_.serialid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_resultid() != 0) {
        _this->_impl_.resultid_ = from._impl_.resultid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_MsgBody();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCSNtyServerInfo: {
        if (oneof_needs_init) {
          _this->_impl_.MsgBody_.csntyserverinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csntyserverinfo_);
        } else {
          _this->_impl_.MsgBody_.csntyserverinfo_->MergeFrom(*from._impl_.MsgBody_.csntyserverinfo_);
        }
        break;
      }
      case kCSReqDeviceInfo: {
        if (oneof_needs_init) {
          _this->_impl_.MsgBody_.csreqdeviceinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csreqdeviceinfo_);
        } else {
          _this->_impl_.MsgBody_.csreqdeviceinfo_->MergeFrom(*from._impl_.MsgBody_.csreqdeviceinfo_);
        }
        break;
      }
      case kCSResDeviceInfo: {
        if (oneof_needs_init) {
          _this->_impl_.MsgBody_.csresdeviceinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csresdeviceinfo_);
        } else {
          _this->_impl_.MsgBody_.csresdeviceinfo_->MergeFrom(*from._impl_.MsgBody_.csresdeviceinfo_);
        }
        break;
      }
      case kCSReqSyncPhoto: {
        if (oneof_needs_init) {
          _this->_impl_.MsgBody_.csreqsyncphoto_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csreqsyncphoto_);
        } else {
          _this->_impl_.MsgBody_.csreqsyncphoto_->MergeFrom(*from._impl_.MsgBody_.csreqsyncphoto_);
        }
        break;
      }
      case kCSResSyncPhoto: {
        if (oneof_needs_init) {
          _this->_impl_.MsgBody_.csressyncphoto_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.MsgBody_.csressyncphoto_);
        } else {
          _this->_impl_.MsgBody_.csressyncphoto_->MergeFrom(*from._impl_.MsgBody_.csressyncphoto_);
        }
        break;
      }
      case MSGBODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MsgPkg::CopyFrom(const MsgPkg& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:LocalPhotoSync.MsgPkg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MsgPkg::InternalSwap(MsgPkg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.resultid_)
      + sizeof(MsgPkg::_impl_.resultid_)
      - PROTOBUF_FIELD_OFFSET(MsgPkg, _impl_.serialid_)>(
          reinterpret_cast<char*>(&_impl_.serialid_),
          reinterpret_cast<char*>(&other->_impl_.serialid_));
  swap(_impl_.MsgBody_, other->_impl_.MsgBody_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MsgPkg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSNtyServerInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CSNtyServerInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_._has_bits_);
};

CSNtyServerInfo::CSNtyServerInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSNtyServerInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.CSNtyServerInfo)
}
PROTOBUF_NDEBUG_INLINE CSNtyServerInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::LocalPhotoSync::CSNtyServerInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        rootpath_(arena, from.rootpath_),
        os_(arena, from.os_) {}

CSNtyServerInfo::CSNtyServerInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSNtyServerInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSNtyServerInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSNtyServerInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.tcpport_ = from._impl_.tcpport_;

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.CSNtyServerInfo)
}
PROTOBUF_NDEBUG_INLINE CSNtyServerInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        rootpath_(arena),
        os_(arena) {}

inline void CSNtyServerInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.tcpport_ = {};
}
CSNtyServerInfo::~CSNtyServerInfo() {
  // @@protoc_insertion_point(destructor:LocalPhotoSync.CSNtyServerInfo)
  SharedDtor(*this);
}
inline void CSNtyServerInfo::SharedDtor(MessageLite& self) {
  CSNtyServerInfo& this_ = static_cast<CSNtyServerInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.rootpath_.Destroy();
  this_._impl_.os_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CSNtyServerInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSNtyServerInfo(arena);
}
constexpr auto CSNtyServerInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CSNtyServerInfo),
                                            alignof(CSNtyServerInfo));
}
constexpr auto CSNtyServerInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSNtyServerInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSNtyServerInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CSNtyServerInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSNtyServerInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CSNtyServerInfo>(), &CSNtyServerInfo::ByteSizeLong,
              &CSNtyServerInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_._cached_size_),
          false,
      },
      &CSNtyServerInfo::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSNtyServerInfo_class_data_ =
        CSNtyServerInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSNtyServerInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSNtyServerInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSNtyServerInfo_class_data_.tc_table);
  return CSNtyServerInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 53, 2>
CSNtyServerInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSNtyServerInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::CSNtyServerInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string OS = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.os_)}},
    // uint32 TcpPort = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CSNtyServerInfo, _impl_.tcpport_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.tcpport_)}},
    // string Name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.name_)}},
    // string RootPath = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.rootpath_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 TcpPort = 1;
    {PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.tcpport_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string Name = 2;
    {PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string RootPath = 3;
    {PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.rootpath_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string OS = 4;
    {PROTOBUF_FIELD_OFFSET(CSNtyServerInfo, _impl_.os_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\4\10\2\0\0\0"
    "LocalPhotoSync.CSNtyServerInfo"
    "Name"
    "RootPath"
    "OS"
  }},
};
PROTOBUF_NOINLINE void CSNtyServerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:LocalPhotoSync.CSNtyServerInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.rootpath_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.os_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.tcpport_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CSNtyServerInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CSNtyServerInfo& this_ = static_cast<const CSNtyServerInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CSNtyServerInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CSNtyServerInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:LocalPhotoSync.CSNtyServerInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 TcpPort = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_tcpport() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_tcpport(), target);
    }
  }

  // string Name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSNtyServerInfo.Name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string RootPath = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_rootpath().empty()) {
      const ::std::string& _s = this_._internal_rootpath();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSNtyServerInfo.RootPath");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string OS = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_os().empty()) {
      const ::std::string& _s = this_._internal_os();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSNtyServerInfo.OS");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LocalPhotoSync.CSNtyServerInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CSNtyServerInfo::ByteSizeLong(const MessageLite& base) {
  const CSNtyServerInfo& this_ = static_cast<const CSNtyServerInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CSNtyServerInfo::ByteSizeLong() const {
  const CSNtyServerInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LocalPhotoSync.CSNtyServerInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string Name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string RootPath = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_rootpath().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rootpath());
      }
    }
    // string OS = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_os().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_os());
      }
    }
    // uint32 TcpPort = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_tcpport() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_tcpport());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CSNtyServerInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CSNtyServerInfo*>(&to_msg);
  auto& from = static_cast<const CSNtyServerInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:LocalPhotoSync.CSNtyServerInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_rootpath().empty()) {
        _this->_internal_set_rootpath(from._internal_rootpath());
      } else {
        if (_this->_impl_.rootpath_.IsDefault()) {
          _this->_internal_set_rootpath("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_os().empty()) {
        _this->_internal_set_os(from._internal_os());
      } else {
        if (_this->_impl_.os_.IsDefault()) {
          _this->_internal_set_os("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_tcpport() != 0) {
        _this->_impl_.tcpport_ = from._impl_.tcpport_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CSNtyServerInfo::CopyFrom(const CSNtyServerInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:LocalPhotoSync.CSNtyServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CSNtyServerInfo::InternalSwap(CSNtyServerInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rootpath_, &other->_impl_.rootpath_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.os_, &other->_impl_.os_, arena);
  swap(_impl_.tcpport_, other->_impl_.tcpport_);
}

::google::protobuf::Metadata CSNtyServerInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSReqDeviceInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CSReqDeviceInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_._has_bits_);
};

CSReqDeviceInfo::CSReqDeviceInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSReqDeviceInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.CSReqDeviceInfo)
}
PROTOBUF_NDEBUG_INLINE CSReqDeviceInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::LocalPhotoSync::CSReqDeviceInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        deviceid_(arena, from.deviceid_),
        path_(arena, from.path_) {}

CSReqDeviceInfo::CSReqDeviceInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSReqDeviceInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSReqDeviceInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSReqDeviceInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.CSReqDeviceInfo)
}
PROTOBUF_NDEBUG_INLINE CSReqDeviceInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        deviceid_(arena),
        path_(arena) {}

inline void CSReqDeviceInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CSReqDeviceInfo::~CSReqDeviceInfo() {
  // @@protoc_insertion_point(destructor:LocalPhotoSync.CSReqDeviceInfo)
  SharedDtor(*this);
}
inline void CSReqDeviceInfo::SharedDtor(MessageLite& self) {
  CSReqDeviceInfo& this_ = static_cast<CSReqDeviceInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.deviceid_.Destroy();
  this_._impl_.path_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CSReqDeviceInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSReqDeviceInfo(arena);
}
constexpr auto CSReqDeviceInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CSReqDeviceInfo),
                                            alignof(CSReqDeviceInfo));
}
constexpr auto CSReqDeviceInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSReqDeviceInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSReqDeviceInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CSReqDeviceInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSReqDeviceInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CSReqDeviceInfo>(), &CSReqDeviceInfo::ByteSizeLong,
              &CSReqDeviceInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_._cached_size_),
          false,
      },
      &CSReqDeviceInfo::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSReqDeviceInfo_class_data_ =
        CSReqDeviceInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSReqDeviceInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSReqDeviceInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSReqDeviceInfo_class_data_.tc_table);
  return CSReqDeviceInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 51, 2>
CSReqDeviceInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSReqDeviceInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::CSReqDeviceInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Path = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_.path_)}},
    // string DeviceID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_.deviceid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string DeviceID = 1;
    {PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_.deviceid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Path = 2;
    {PROTOBUF_FIELD_OFFSET(CSReqDeviceInfo, _impl_.path_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\10\4\0\0\0\0\0"
    "LocalPhotoSync.CSReqDeviceInfo"
    "DeviceID"
    "Path"
  }},
};
PROTOBUF_NOINLINE void CSReqDeviceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:LocalPhotoSync.CSReqDeviceInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.deviceid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.path_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CSReqDeviceInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CSReqDeviceInfo& this_ = static_cast<const CSReqDeviceInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CSReqDeviceInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CSReqDeviceInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:LocalPhotoSync.CSReqDeviceInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string DeviceID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_deviceid().empty()) {
      const ::std::string& _s = this_._internal_deviceid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSReqDeviceInfo.DeviceID");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string Path = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_path().empty()) {
      const ::std::string& _s = this_._internal_path();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSReqDeviceInfo.Path");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LocalPhotoSync.CSReqDeviceInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CSReqDeviceInfo::ByteSizeLong(const MessageLite& base) {
  const CSReqDeviceInfo& this_ = static_cast<const CSReqDeviceInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CSReqDeviceInfo::ByteSizeLong() const {
  const CSReqDeviceInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LocalPhotoSync.CSReqDeviceInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string DeviceID = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_deviceid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_deviceid());
      }
    }
    // string Path = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_path().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_path());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CSReqDeviceInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CSReqDeviceInfo*>(&to_msg);
  auto& from = static_cast<const CSReqDeviceInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:LocalPhotoSync.CSReqDeviceInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_deviceid().empty()) {
        _this->_internal_set_deviceid(from._internal_deviceid());
      } else {
        if (_this->_impl_.deviceid_.IsDefault()) {
          _this->_internal_set_deviceid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_path().empty()) {
        _this->_internal_set_path(from._internal_path());
      } else {
        if (_this->_impl_.path_.IsDefault()) {
          _this->_internal_set_path("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CSReqDeviceInfo::CopyFrom(const CSReqDeviceInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:LocalPhotoSync.CSReqDeviceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CSReqDeviceInfo::InternalSwap(CSReqDeviceInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.deviceid_, &other->_impl_.deviceid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata CSReqDeviceInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSResDeviceInfo::_Internal {
 public:
};

CSResDeviceInfo::CSResDeviceInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSResDeviceInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.CSResDeviceInfo)
}
CSResDeviceInfo::CSResDeviceInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSResDeviceInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSResDeviceInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSResDeviceInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.CSResDeviceInfo)
}

inline void* PROTOBUF_NONNULL CSResDeviceInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSResDeviceInfo(arena);
}
constexpr auto CSResDeviceInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CSResDeviceInfo),
                                            alignof(CSResDeviceInfo));
}
constexpr auto CSResDeviceInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSResDeviceInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSResDeviceInfo::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CSResDeviceInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSResDeviceInfo::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CSResDeviceInfo>(), &CSResDeviceInfo::ByteSizeLong,
              &CSResDeviceInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSResDeviceInfo, _impl_._cached_size_),
          false,
      },
      &CSResDeviceInfo::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSResDeviceInfo_class_data_ =
        CSResDeviceInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSResDeviceInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSResDeviceInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSResDeviceInfo_class_data_.tc_table);
  return CSResDeviceInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
CSResDeviceInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSResDeviceInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::CSResDeviceInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata CSResDeviceInfo::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSReqSyncPhoto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CSReqSyncPhoto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_._has_bits_);
};

CSReqSyncPhoto::CSReqSyncPhoto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSReqSyncPhoto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.CSReqSyncPhoto)
}
PROTOBUF_NDEBUG_INLINE CSReqSyncPhoto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::LocalPhotoSync::CSReqSyncPhoto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_),
        data_(arena, from.data_) {}

CSReqSyncPhoto::CSReqSyncPhoto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSReqSyncPhoto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSReqSyncPhoto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSReqSyncPhoto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, size_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, size_),
           offsetof(Impl_, crc32_) -
               offsetof(Impl_, size_) +
               sizeof(Impl_::crc32_));

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.CSReqSyncPhoto)
}
PROTOBUF_NDEBUG_INLINE CSReqSyncPhoto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena),
        data_(arena) {}

inline void CSReqSyncPhoto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, size_),
           0,
           offsetof(Impl_, crc32_) -
               offsetof(Impl_, size_) +
               sizeof(Impl_::crc32_));
}
CSReqSyncPhoto::~CSReqSyncPhoto() {
  // @@protoc_insertion_point(destructor:LocalPhotoSync.CSReqSyncPhoto)
  SharedDtor(*this);
}
inline void CSReqSyncPhoto::SharedDtor(MessageLite& self) {
  CSReqSyncPhoto& this_ = static_cast<CSReqSyncPhoto&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CSReqSyncPhoto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSReqSyncPhoto(arena);
}
constexpr auto CSReqSyncPhoto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CSReqSyncPhoto),
                                            alignof(CSReqSyncPhoto));
}
constexpr auto CSReqSyncPhoto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSReqSyncPhoto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSReqSyncPhoto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CSReqSyncPhoto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSReqSyncPhoto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CSReqSyncPhoto>(), &CSReqSyncPhoto::ByteSizeLong,
              &CSReqSyncPhoto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_._cached_size_),
          false,
      },
      &CSReqSyncPhoto::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSReqSyncPhoto_class_data_ =
        CSReqSyncPhoto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSReqSyncPhoto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSReqSyncPhoto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSReqSyncPhoto_class_data_.tc_table);
  return CSReqSyncPhoto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 46, 2>
CSReqSyncPhoto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSReqSyncPhoto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::CSReqSyncPhoto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.filename_)}},
    // uint64 Size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CSReqSyncPhoto, _impl_.size_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.size_)}},
    // uint64 Offset = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CSReqSyncPhoto, _impl_.offset_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.offset_)}},
    // uint64 Timestamp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CSReqSyncPhoto, _impl_.timestamp_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.timestamp_)}},
    // bool HasNextPkt = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CSReqSyncPhoto, _impl_.hasnextpkt_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.hasnextpkt_)}},
    // bytes Data = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 1, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.data_)}},
    // uint32 Crc32 = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CSReqSyncPhoto, _impl_.crc32_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.crc32_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Filename = 1;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 Size = 2;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Offset = 3;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.offset_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 Timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.timestamp_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool HasNextPkt = 5;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.hasnextpkt_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bytes Data = 6;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 Crc32 = 7;
    {PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.crc32_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\35\10\0\0\0\0\0\0"
    "LocalPhotoSync.CSReqSyncPhoto"
    "Filename"
  }},
};
PROTOBUF_NOINLINE void CSReqSyncPhoto::Clear() {
// @@protoc_insertion_point(message_clear_start:LocalPhotoSync.CSReqSyncPhoto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000007cU)) {
    ::memset(&_impl_.size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.crc32_) -
        reinterpret_cast<char*>(&_impl_.size_)) + sizeof(_impl_.crc32_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CSReqSyncPhoto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CSReqSyncPhoto& this_ = static_cast<const CSReqSyncPhoto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CSReqSyncPhoto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CSReqSyncPhoto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:LocalPhotoSync.CSReqSyncPhoto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string Filename = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LocalPhotoSync.CSReqSyncPhoto.Filename");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint64 Size = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_size(), target);
    }
  }

  // uint64 Offset = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_offset() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_offset(), target);
    }
  }

  // uint64 Timestamp = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_timestamp() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_timestamp(), target);
    }
  }

  // bool HasNextPkt = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_hasnextpkt() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_hasnextpkt(), target);
    }
  }

  // bytes Data = 6;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // uint32 Crc32 = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_crc32() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_crc32(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LocalPhotoSync.CSReqSyncPhoto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CSReqSyncPhoto::ByteSizeLong(const MessageLite& base) {
  const CSReqSyncPhoto& this_ = static_cast<const CSReqSyncPhoto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CSReqSyncPhoto::ByteSizeLong() const {
  const CSReqSyncPhoto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:LocalPhotoSync.CSReqSyncPhoto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string Filename = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bytes Data = 6;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // uint64 Size = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_size());
      }
    }
    // uint64 Offset = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_offset() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_offset());
      }
    }
    // uint64 Timestamp = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // bool HasNextPkt = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_hasnextpkt() != 0) {
        total_size += 2;
      }
    }
    // uint32 Crc32 = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_crc32() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_crc32());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CSReqSyncPhoto::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CSReqSyncPhoto*>(&to_msg);
  auto& from = static_cast<const CSReqSyncPhoto&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:LocalPhotoSync.CSReqSyncPhoto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_offset() != 0) {
        _this->_impl_.offset_ = from._impl_.offset_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_hasnextpkt() != 0) {
        _this->_impl_.hasnextpkt_ = from._impl_.hasnextpkt_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_crc32() != 0) {
        _this->_impl_.crc32_ = from._impl_.crc32_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CSReqSyncPhoto::CopyFrom(const CSReqSyncPhoto& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:LocalPhotoSync.CSReqSyncPhoto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CSReqSyncPhoto::InternalSwap(CSReqSyncPhoto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.crc32_)
      + sizeof(CSReqSyncPhoto::_impl_.crc32_)
      - PROTOBUF_FIELD_OFFSET(CSReqSyncPhoto, _impl_.size_)>(
          reinterpret_cast<char*>(&_impl_.size_),
          reinterpret_cast<char*>(&other->_impl_.size_));
}

::google::protobuf::Metadata CSReqSyncPhoto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSResSyncPhoto::_Internal {
 public:
};

CSResSyncPhoto::CSResSyncPhoto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSResSyncPhoto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:LocalPhotoSync.CSResSyncPhoto)
}
CSResSyncPhoto::CSResSyncPhoto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSResSyncPhoto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSResSyncPhoto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSResSyncPhoto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LocalPhotoSync.CSResSyncPhoto)
}

inline void* PROTOBUF_NONNULL CSResSyncPhoto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSResSyncPhoto(arena);
}
constexpr auto CSResSyncPhoto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CSResSyncPhoto),
                                            alignof(CSResSyncPhoto));
}
constexpr auto CSResSyncPhoto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSResSyncPhoto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSResSyncPhoto::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CSResSyncPhoto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSResSyncPhoto::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CSResSyncPhoto>(), &CSResSyncPhoto::ByteSizeLong,
              &CSResSyncPhoto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSResSyncPhoto, _impl_._cached_size_),
          false,
      },
      &CSResSyncPhoto::kDescriptorMethods,
      &descriptor_table_csmsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSResSyncPhoto_class_data_ =
        CSResSyncPhoto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSResSyncPhoto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSResSyncPhoto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSResSyncPhoto_class_data_.tc_table);
  return CSResSyncPhoto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
CSResSyncPhoto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSResSyncPhoto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LocalPhotoSync::CSResSyncPhoto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata CSResSyncPhoto::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace LocalPhotoSync
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_csmsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
