syntax = "proto3";

package LocalPhotoSync;


message MsgPkg
{
    int32 ResultID = 1;     //错误码
    uint64 SerialID = 2;    //序列号
    oneof MsgBody
    {

        CSNtyServerInfo CSNtyServerInfo = 50;       //udp 广播服务器消息

        CSReqDeviceInfo CSReqDeviceInfo = 101;
        CSResDeviceInfo CSResDeviceInfo = 102;
        
    }
}

message CSNtyServerInfo
{
    uint32 TcpPort = 1;     //tcp port
    string Name = 2;        //服务器名称
    string RootPath = 3;    //根目录
    string OS = 4;          //操作系统
}

message CSReqDeviceInfo
{
    string DeviceID = 1;    //设备ID
    string Path = 2;        //保存路径
}

message CSResDeviceInfo
{
    
}
