// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msgid.proto
// Protobuf C++ Version: 6.33.0

#include "msgid.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace LocalPhotoSync {
}  // namespace LocalPhotoSync
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_msgid_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_msgid_2eproto = nullptr;
const ::uint32_t TableStruct_msgid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_msgid_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013msgid.proto\022\016LocalPhotoSync*\212\001\n\005MSGID\022"
    "\013\n\007ID_None\020\000\022\026\n\022ID_CSNtyServerInfo\0202\022\026\n\022"
    "ID_CSReqDeviceInfo\020e\022\026\n\022ID_CSResDeviceIn"
    "fo\020f\022\025\n\021ID_CSReqSyncPhoto\020g\022\025\n\021ID_CSResS"
    "yncPhoto\020hb\006proto3"
};
static ::absl::once_flag descriptor_table_msgid_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_msgid_2eproto = {
    false,
    false,
    178,
    descriptor_table_protodef_msgid_2eproto,
    "msgid.proto",
    &descriptor_table_msgid_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_msgid_2eproto::offsets,
    file_level_enum_descriptors_msgid_2eproto,
    file_level_service_descriptors_msgid_2eproto,
};
namespace LocalPhotoSync {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MSGID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msgid_2eproto);
  return file_level_enum_descriptors_msgid_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MSGID_internal_data_[] = {
    65536u, 128u, 0u, 131072u, 0u, 240u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace LocalPhotoSync
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_msgid_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
