// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msgid.proto
// Protobuf C++ Version: 6.33.0

#ifndef msgid_2eproto_2epb_2eh
#define msgid_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msgid_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msgid_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_msgid_2eproto;
}  // extern "C"
namespace LocalPhotoSync {
enum MSGID : int;
extern const uint32_t MSGID_internal_data_[];
}  // namespace LocalPhotoSync
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::LocalPhotoSync::MSGID_internal_data_>
    internal::EnumTraitsImpl::value<::LocalPhotoSync::MSGID>;
}  // namespace protobuf
}  // namespace google

namespace LocalPhotoSync {
enum MSGID : int {
  ID_None = 0,
  ID_CSNtyServerInfo = 50,
  ID_CSReqDeviceInfo = 101,
  ID_CSResDeviceInfo = 102,
  ID_CSReqSyncPhoto = 103,
  ID_CSResSyncPhoto = 104,
  MSGID_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MSGID_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MSGID_internal_data_[];
inline constexpr MSGID MSGID_MIN =
    static_cast<MSGID>(0);
inline constexpr MSGID MSGID_MAX =
    static_cast<MSGID>(104);
inline bool MSGID_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, MSGID_internal_data_);
}
inline constexpr int MSGID_ARRAYSIZE = 104 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MSGID_descriptor();
template <typename T>
const ::std::string& MSGID_Name(T value) {
  static_assert(::std::is_same<T, MSGID>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MSGID_Name().");
  return ::google::protobuf::internal::NameOfEnum(MSGID_descriptor(), value);
}
inline bool MSGID_Parse(
    ::absl::string_view name, MSGID* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSGID>(MSGID_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace LocalPhotoSync


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::LocalPhotoSync::MSGID> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::LocalPhotoSync::MSGID>() {
  return ::LocalPhotoSync::MSGID_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // msgid_2eproto_2epb_2eh
